sudo: required

env:
  - CI=true

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t vnscriptkid/react-app .

script:
  - docker run vnscriptkid/react-app npm run test -- --watchAll=false --coverage --watch=false