version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - /usr/app/node_modules
      - /workspace/docker/frontend:/usr/app
  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /usr/app/node_modules
  #     - /workspace/docker/frontend:/usr/app
  #   command: ["npm", "run", "test"] # overwrite CMD in Dockerfile
    